# Generated by Django 5.2.5 on 2025-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorylog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
