# Generated by Django 5.2.5 on 2025-10-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customtest', '0002_alter_memorylog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorylog',
            old_name='id',
            new_name='memorylog_id',
        ),
    ]
