# Generated by Django 5.2.5 on 2025-09-15 15:01

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True, verbose_name='Tag Organizzazione')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Organizzazione')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tel', models.CharField(blank=True, max_length=63, null=True, verbose_name='Telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('free_trial', models.BooleanField(default=False, verbose_name='Periodo di prova')),
                ('free_trial_finish', models.DateField(blank=True, null=True, verbose_name='Fine periodo di prova')),
                ('account_expires', models.DateField(blank=True, null=True, verbose_name='Scadenza account')),
                ('domain', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=app.models.org_logo_path, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Organizzazione',
                'verbose_name_plural': 'Organizzazioni',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Chiaro'), ('dark', 'Scuro')], default='light', max_length=512, verbose_name='Tema')),
                ('img', models.ImageField(blank=True, null=True, upload_to=app.models.user_imgs_path, verbose_name='Immagine del profilo')),
                ('signature', models.ImageField(blank=True, null=True, upload_to=app.models.user_signature_path, verbose_name='Firma')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.organization', verbose_name='Organizzazione')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilo utente',
                'verbose_name_plural': 'Profili utente',
            },
        ),
    ]
