# Generated by Django 5.2.5 on 2025-08-20 14:11

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme', models.CharField(choices=[('light', 'Chiaro'), ('dark', 'Scuro')], default='light', max_length=512, verbose_name='Tema')),
                ('img', models.ImageField(blank=True, null=True, upload_to='app/appuser/imgs', verbose_name='Immagine del profilo')),
                ('_has_accepted_tec', models.BooleanField(default=False, verbose_name='Ha accettato i termini e condizioni')),
            ],
            options={
                'verbose_name': 'Application User',
                'verbose_name_plural': 'Application Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
