# Generated by Django 5.2.5 on 2025-10-11 23:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='account_expires',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='free_trial',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='free_trial_finish',
        ),
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data di creazione'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima modifica'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='tag')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('validity', models.DateField(blank=True, null=True, verbose_name='Valido fino al')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durata')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima modifica')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.organization', verbose_name='Organizzazione')),
            ],
        ),
    ]
