# Generated by Django 5.2.5 on 2025-11-03 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_remove_organization_account_expires_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima modifica')),
                ('cognome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cognome Defunto')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Defunto')),
                ('sesso', models.CharField(blank=True, choices=[('F', 'Femmina'), ('M', 'Maschio')], max_length=1, null=True, verbose_name='Sesso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.organization', verbose_name='Organizzazione')),
            ],
        ),
    ]
