# Generated by Django 5.2.5 on 2025-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaDefunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cognome Defunto')),
                ('nome', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome Defunto')),
                ('sesso', models.CharField(blank=True, choices=[('F', 'Femmina'), ('M', 'Maschio')], max_length=1, null=True, verbose_name='Sesso')),
                ('cittadinanza', models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Cittadinanza')),
                ('luogo_nascita', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Luogo di Nascita')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di Nascita')),
                ('comune_residenza', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune di Residenza')),
                ('via_residenza', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Via di Residenza')),
                ('codice_fiscale', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Codice Fiscale')),
                ('doc_ric_def', models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Documento di Riconoscimento Defunto')),
                ('ente_doc_def', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ente di Rilascio Documento Defunto')),
                ('data_doc_def', models.DateField(blank=True, null=True, verbose_name='Data di Rilascio Documento Defunto')),
                ('comune_decesso', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune del Decesso')),
                ('via_decesso', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Via del Decesso')),
                ('ospedale', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ospedale')),
                ('reparto_ospedaliero', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Reparto Ospedaliero')),
                ('data_morte', models.DateField(blank=True, null=True, verbose_name='Data di Morte')),
                ('ora_morte', models.TimeField(blank=True, null=True, verbose_name='Orario di Morte')),
                ('tipo_luogo_salma', models.SmallIntegerField(blank=True, choices=[(1, 'Abitazione privata'), (2, 'Istituto / Casa di riposo'), (3, 'struttura obitoriale')], null=True)),
                ('comune_salma', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Comune dell'osservazione salma")),
                ('via_salma', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Via dell'osservazione salma")),
                ('professione', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Professione')),
                ('stato_civile', models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Stato Civile')),
                ('cognome_parente', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cognome Parente')),
                ('nome_parente', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome Parente')),
                ('data_nascita_parente', models.DateField(blank=True, null=True, verbose_name='Data di Nascita Parente')),
                ('doc_ric_par', models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Documento di Riconoscimento Parente')),
                ('ente_doc_par', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ente di Rilascio Documento Parente')),
                ('data_doc_par', models.DateField(blank=True, null=True, verbose_name='Data di Rilascio Documento Parente')),
                ('tel_famiglia', models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Telefono Famiglia')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('altro', models.TextField(blank=True, default='', null=True, verbose_name='Altre Informazioni')),
                ('chiesa', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Chiesa')),
                ('comune_chiesa', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune Chiesa')),
                ('data_ora_funerale', models.DateTimeField(blank=True, null=True, verbose_name='Data e Ora del Funerale')),
                ('data_inumazione', models.DateField(blank=True, null=True, verbose_name='Data di inumazione')),
                ('ora_inumazione', models.TimeField(blank=True, null=True, verbose_name='Orario di inumazione')),
                ('comune_inumazione', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune di sepoltura (e provincia)')),
                ('ubicazione_feretro', models.TextField(blank=True, default='', null=True, verbose_name='Ubicazione Feretro')),
                ('affissione_manifesti', models.BooleanField(default=False, verbose_name='Affissione Manifesti')),
                ('medico_curante', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Medico Curante')),
                ('fioraio', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Fioraio')),
                ('lutto_casa', models.BooleanField(default=False, verbose_name='Lutto a Casa')),
                ('corteo_da_casa', models.BooleanField(default=False, verbose_name='Corteo da Casa')),
                ('corteo_da_ospedale', models.BooleanField(default=False, verbose_name='Corteo da Ospedale')),
                ('pass_solo_auto', models.BooleanField(default=False, verbose_name='Passaggio da Casa Solo Auto')),
                ('pass_casa_per_corteo', models.BooleanField(default=False, verbose_name='Passaggio da Casa per Iniziare il Corteo')),
                ('dirett_in_chiesa', models.BooleanField(default=False, verbose_name='Direttamente in Chiesa')),
                ('sala_commiato', models.BooleanField(default=False, verbose_name='Sala del Commiato')),
                ('tutto_in_auto', models.BooleanField(default=False, verbose_name='Tutto in Auto')),
                ('auto_chiesa_cimitero', models.BooleanField(default=False, verbose_name='Auto Chiesa / Cimitero')),
                ('data_incarico', models.DateField(blank=True, null=True, verbose_name='Data di Incarico')),
                ('necrofori', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Necrofori')),
                ('fattura_n', models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Fattura N.')),
                ('articolo_cofano_funebre', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Articolo Cofano Funebre')),
                ('targa_autofunebre', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Targa autofunebre')),
                ('altro_servizi', models.TextField(blank=True, default='', null=True, verbose_name='Altro (servizi)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima modifica')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documenti/', verbose_name='File')),
                ('nome', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome File')),
            ],
        ),
    ]
