# Generated by Django 5.2.5 on 2025-08-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaDefunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cognome')),
                ('nome', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome')),
                ('luogo_nascita', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Luogo di Nascita')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di Nascita')),
                ('comune_residenza', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune di Residenza')),
                ('via_residenza', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Via di Residenza')),
                ('comune_decesso', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune del Decesso')),
                ('via_decesso', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Via del Decesso')),
                ('ospedale', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ospedale')),
                ('reparto_ospedaliero', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Reparto Ospedaliero')),
                ('data_ora_morte', models.DateTimeField(blank=True, null=True, verbose_name='Data e Ora del Decesso')),
                ('professione', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Professione')),
                ('stato_civile', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Stato Civile')),
                ('cognome_coniuge', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cognome Coniuge')),
                ('nome_coniuge', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome Coniuge')),
                ('data_nascita_coniuge', models.DateField(blank=True, null=True, verbose_name='Data di Nascita Coniuge')),
                ('data_matrimonio', models.DateField(blank=True, null=True, verbose_name='Data di Matrimonio')),
                ('tel_famiglia', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Telefono Famiglia')),
                ('chiesa', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Chiesa')),
                ('data_ora_funerale', models.DateTimeField(blank=True, null=True, verbose_name='Data e Ora del Funerale')),
                ('cimitero', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cimitero')),
                ('ubicazione_feretro', models.TextField(blank=True, default='', null=True, verbose_name='Ubicazione Feretro')),
                ('affissione_manifesti', models.BooleanField(default=False, verbose_name='Affissione Manifesti')),
                ('medico_curante', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Medico Curante')),
                ('fioraio', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Fioraio')),
                ('codice_fiscale', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Codice Fiscale')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('altro', models.TextField(blank=True, default='', null=True, verbose_name='Altro')),
                ('lutto_casa', models.BooleanField(default=False, verbose_name='Lutto a Casa')),
                ('corteo_da_casa', models.BooleanField(default=False, verbose_name='Corteo da Casa')),
                ('corteo_da_ospedale', models.BooleanField(default=False, verbose_name='Corteo da Ospedale')),
                ('pass_solo_auto', models.BooleanField(default=False, verbose_name='Passaggio da Casa Solo Auto')),
                ('pass_casa_per_corteo', models.BooleanField(default=False, verbose_name='Passaggio da Casa per Iniziare il Corteo')),
                ('dirett_in_chiesa', models.BooleanField(default=False, verbose_name='Direttamente in Chiesa')),
                ('sala_commiato', models.BooleanField(default=False, verbose_name='Sala del Commiato')),
                ('tutto_in_auto', models.BooleanField(default=False, verbose_name='Tutto in Auto')),
                ('auto_chiesa_cimitero', models.BooleanField(default=False, verbose_name='Auto Chiesa / Cimitero')),
                ('necrofori', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Necrofori')),
                ('fattura_n', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Fattura N.')),
                ('articolo_cofano_funebre', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Articolo Cofano Funebre')),
                ('altro_servizi', models.TextField(blank=True, default='', null=True, verbose_name='Altro (servizi)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima modifica')),
            ],
        ),
    ]
