# Generated by Django 5.2.5 on 2025-08-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='codice_fiscale',
        ),
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='cognome_coniuge',
        ),
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='data_matrimonio',
        ),
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='data_nascita_coniuge',
        ),
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='nome_coniuge',
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='cognome_parente',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cognome Parente'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='data_doc_def',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Rilascio Documento Defunto'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='data_doc_par',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Rilascio Documento Parente'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='data_nascita_parente',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Nascita Parente'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='doc_ric_def',
            field=models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Documento di Riconoscimento Defunto'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='doc_ric_par',
            field=models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Documento di Riconoscimento Parente'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='ente_doc_def',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ente di Rilascio Documento Defunto'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='ente_doc_par',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ente di Rilascio Documento Parente'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='nome_parente',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome Parente'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='altro',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Altre Informazioni'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='cognome',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cognome Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_ora_morte',
            field=models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Data e Ora di Morte'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='fattura_n',
            field=models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Fattura N.'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='stato_civile',
            field=models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Stato Civile'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='tel_famiglia',
            field=models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Telefono Famiglia'),
        ),
    ]
