# Generated by Django 5.2.5 on 2025-08-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documenti/')),
            ],
        ),
    ]
