# Generated by Django 5.2.5 on 2025-09-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Ordine in lista'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='ora_decesso',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora del decesso (formato hh:mm)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='tipo_luogo_salma',
            field=models.CharField(blank=True, choices=[('Abitazione privata', 'Abitazione privata'), ('Istituto / Casa di riposo / Struttura obitoriale / Ospedale', 'Istituto / Casa di riposo / Struttura obitoriale / Ospedale')], null=True, verbose_name='Luogo di osservazione della salma'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='via_salma',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Via dell'osservazione salma"),
        ),
    ]
