# Generated by Django 5.2.5 on 2025-08-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anagraficadefunto',
            old_name='luogo_nascita',
            new_name='comune_nascita',
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='provincia_chiesa',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Provincia della Chiesa'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='provincia_decesso',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Provincia del Decesso'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='provincia_inumazione',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Provincia di sepoltura'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='provincia_nascita',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Provincia di Nascita'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='provincia_residenza',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Provincia di Residenza'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='provincia_salma',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name="Provincia dell'osservazione salma"),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='comune_inumazione',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune di sepoltura'),
        ),
    ]
