# Generated by Django 5.2.5 on 2025-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='via_salma',
            field=models.CharField(max_length=255, null=True, verbose_name="Via dell'osservazione salma"),
        ),
    ]
