# Generated by Django 5.2.5 on 2025-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='sosta_feretro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sosta feretro'),
        ),
    ]
