# Generated by Django 5.2.5 on 2025-08-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fields',
            field=models.JSONField(null=True, verbose_name='Campi'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(upload_to='documenti/', verbose_name='File'),
        ),
    ]
