# Generated by Django 5.2.5 on 2025-09-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0002_documento_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='sesso_par',
            field=models.CharField(blank=True, choices=[('F', 'Femmina'), ('M', 'Maschio')], max_length=1, null=True, verbose_name='Sesso Parente'),
        ),
    ]
