# Generated by Django 5.2.5 on 2025-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0002_rename_luogo_nascita_anagraficadefunto_comune_nascita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='comune_nascita',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune di Nascita'),
        ),
    ]
