# Generated by Django 5.2.5 on 2025-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0002_alter_anagraficadefunto_codice_fiscale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_doc_def',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Rilascio Documento Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_doc_par',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Rilascio Documento Parente'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_incarico',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Incarico'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_morte',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Morte'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_nascita',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Nascita'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_nascita_parente',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Nascita Parente'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_ora_funerale',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Ora del Funerale'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_ora_partenza',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Ora della partenza del corteo'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='tipo_luogo_salma',
            field=models.CharField(blank=True, choices=[('Abitazione privata', 'Abitazione privata'), ('Istituto / Casa di riposo', 'Istituto / Casa di riposo'), ('struttura obitoriale', 'struttura obitoriale')], null=True),
        ),
    ]
