# Generated by Django 5.2.5 on 2025-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0002_remove_anagraficadefunto_codice_fiscale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome File'),
        ),
    ]
