# Generated by Django 5.2.5 on 2025-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0003_documento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fields',
            field=models.JSONField(blank=True, null=True, verbose_name='Campi'),
        ),
    ]
