# Generated by Django 5.2.5 on 2025-09-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0003_anagraficadefunto_sesso_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='comune_nascita_par',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comune di Nascita Parente'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='provincia_nascita_par',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia di Nascita Parente (sigla)'),
        ),
    ]
