# Generated by Django 5.2.5 on 2025-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0003_alter_anagraficadefunto_comune_nascita'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='n_doc_ric_def',
            field=models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Numero Documento di Riconoscimento Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='doc_ric_def',
            field=models.CharField(blank=True, default='', max_length=63, null=True, verbose_name='Tipo Documento di Riconoscimento Defunto'),
        ),
    ]
