# Generated by Django 5.2.5 on 2025-09-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0003_alter_anagraficadefunto_data_doc_def_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='comune_inumazione',
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='comune_sepoltura',
            field=models.CharField(max_length=255, null=True, verbose_name='Comune di sepoltura'),
        ),
    ]
