# Generated by Django 5.2.5 on 2025-08-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0004_alter_documento_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='data_ora_morte',
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='data_morte',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Nascita'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='ora_morte',
            field=models.TimeField(blank=True, null=True, verbose_name='Orario di Morte'),
        ),
    ]
