# Generated by Django 5.2.5 on 2025-09-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0004_anagraficadefunto_comune_nascita_par_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anagraficadefunto',
            old_name='indirizzo_residenza_par',
            new_name='via_residenza_par',
        ),
    ]
