# Generated by Django 5.2.5 on 2025-09-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0004_remove_anagraficadefunto_comune_inumazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='comune_residenza_par',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comune di residenza parente'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='indirizzo_residenza_par',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Via di residenza parente'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='provincia_residenza_par',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia di residenza parente (sigla)'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='tipo_parente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grado di parentela'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='tipo_luogo_salma',
            field=models.CharField(blank=True, choices=[('Abitazione privata', 'Abitazione privata'), ('Istituto / Casa di riposo', 'Istituto / Casa di riposo'), ('Struttura obitoriale', 'Struttura obitoriale')], null=True),
        ),
    ]
