# Generated by Django 5.2.5 on 2025-08-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0004_anagraficadefunto_n_doc_ric_def_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='foglio_intestato',
            field=models.FileField(null=True, upload_to='documenti/fogli_intestati/', verbose_name='Foglio Intestato'),
        ),
    ]
