# Generated by Django 5.2.5 on 2025-08-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0005_documento_foglio_intestato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='foglio_intestato',
            field=models.FileField(blank=True, null=True, upload_to='documenti/fogli_intestati/', verbose_name='Foglio Intestato'),
        ),
    ]
