# Generated by Django 5.2.5 on 2025-08-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0005_remove_anagraficadefunto_data_ora_morte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='fields',
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_morte',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Morte'),
        ),
    ]
