# Generated by Django 5.2.5 on 2025-09-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0005_rename_indirizzo_residenza_par_anagraficadefunto_via_residenza_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='codice_fiscale_par',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice Fiscale parente'),
        ),
    ]
