# Generated by Django 5.2.5 on 2025-08-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0006_remove_documento_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documenti/mediafiles/', verbose_name='File')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descrizione')),
                ('document', models.ManyToManyField(to='docdefunto.documento')),
            ],
        ),
    ]
