# Generated by Django 5.2.5 on 2025-09-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0006_anagraficadefunto_codice_fiscale_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='processo_sepoltura',
            field=models.CharField(blank=True, choices=[('Cremazione', 'Cremazione'), ('Tradizionale', 'Tradizionale')], null=True, verbose_name='Processo Sepoltura'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='doc_ric_def',
            field=models.CharField(blank=True, choices=[('C.I.', 'Carta di Identità'), ('Patente', 'Patente'), ('Passaporto', 'Passaporto')], null=True, verbose_name='Tipo Documento di Riconoscimento Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='stato_civile',
            field=models.CharField(blank=True, choices=[('Celibe / nubile', 'Celibe / nubile'), ('Coniugato / unito civilmente', 'Coniugato / unito civilmente con'), ('Vedovo', 'Vedovo di'), ('Già coniugato / unito civolmente', 'Già coniugato / unito civolmente con')], null=True, verbose_name='Stato Civile'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='ubicazione_feretro',
            field=models.CharField(blank=True, choices=[('Cappella', 'Cappella'), ('Inumazione', 'Inumazione'), ('Tumulazione', 'Tumulazione')], null=True, verbose_name='Ubicazione Feretro'),
        ),
    ]
