# Generated by Django 5.2.5 on 2025-09-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0006_alter_documento_foglio_intestato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='altro',
            field=models.TextField(blank=True, null=True, verbose_name='Altre Informazioni'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='altro_servizi',
            field=models.TextField(blank=True, null=True, verbose_name='Altro (servizi)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='articolo_cofano_funebre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Articolo Cofano Funebre'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='chiesa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chiesa'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='cittadinanza',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Cittadinanza'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='cognome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cognome Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='cognome_parente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cognome Parente'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='comune_chiesa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comune Chiesa'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='comune_decesso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comune del Decesso'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='comune_inumazione',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comune di sepoltura'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='comune_nascita',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comune di Nascita'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='comune_residenza',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comune di Residenza'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='comune_salma',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Comune dell'osservazione salma"),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='doc_ric_def',
            field=models.CharField(blank=True, choices=[('C.I.', 'Carta di Identità'), ('Patente', 'Patente'), ('Passaporto', 'Passaporto')], max_length=10, null=True, verbose_name='Tipo Documento di Riconoscimento Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='doc_ric_par',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Documento di Riconoscimento Parente'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='ente_doc_def',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ente di Rilascio Documento Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='ente_doc_par',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ente di Rilascio Documento Parente'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='fattura_n',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Fattura N.'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='fioraio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fioraio'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='medico_curante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Medico Curante'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='n_doc_ric_def',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Numero Documento di Riconoscimento Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Defunto'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='nome_parente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Parente'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='ospedale',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ospedale'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='professione',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Professione'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='provincia_chiesa',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia della Chiesa (sigla)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='provincia_decesso',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia del Decesso (sigla)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='provincia_inumazione',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia di sepoltura (sigla)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='provincia_nascita',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia di Nascita (sigla)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='provincia_residenza',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia di Residenza (sigla)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='provincia_salma',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="Provincia dell'osservazione salma (sigla)"),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='reparto_ospedaliero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reparto Ospedaliero'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='stato_civile',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Stato Civile'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='targa_autofunebre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Targa autofunebre'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='tel_famiglia',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Telefono Famiglia'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='ubicazione_feretro',
            field=models.TextField(blank=True, null=True, verbose_name='Ubicazione Feretro'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='via_decesso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Via del Decesso'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='via_residenza',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Via di Residenza'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='via_salma',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Via dell'osservazione salma"),
        ),
    ]
