# Generated by Django 5.2.5 on 2025-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0007_alter_anagraficadefunto_altro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='n_doc_ric_par',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Numero Documento di Riconoscimento Parente'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='doc_ric_par',
            field=models.CharField(blank=True, choices=[('C.I.', 'Carta di Identità'), ('Patente', 'Patente'), ('Passaporto', 'Passaporto')], max_length=10, null=True, verbose_name='Documento di Riconoscimento Parente'),
        ),
    ]
