# Generated by Django 5.2.5 on 2025-09-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0008_anagraficadefunto_n_doc_ric_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='cognome_coniuge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cognome Coniuge'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='nome_coniuge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Coniuge'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='stato_civile',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Celibe / nubile'), (2, 'Coniugato / unito civilmente'), (3, 'Vedovo'), (4, 'Già coniugato / unito civolmente')], max_length=127, null=True, verbose_name='Stato Civile'),
        ),
    ]
