# Generated by Django 5.2.5 on 2025-08-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0008_documentstatic_delete_documentmediafile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentStatic',
        ),
    ]
