# Generated by Django 5.2.5 on 2025-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0009_delete_documentstatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='sesso',
            field=models.CharField(blank=True, choices=[('F', 'Femmina'), ('M', 'Maschio')], max_length=1, null=True),
        ),
    ]
