# Generated by Django 5.2.5 on 2025-09-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0009_anagraficadefunto_cognome_coniuge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='stato_civile',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Celibe / nubile'), (2, 'Coniugato / unito civilmente con'), (3, 'Vedovo di'), (4, 'Già coniugato / unito civolmente con')], max_length=127, null=True, verbose_name='Stato Civile'),
        ),
    ]
