# Generated by Django 5.2.5 on 2025-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0010_alter_anagraficadefunto_stato_civile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='data_inumazione',
        ),
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='ora_inumazione',
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='affissione_manifesti',
            field=models.CharField(verbose_name='Comuni affissione manifesti'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_doc_def',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Rilascio Documento Defunto (formato GG/MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_doc_par',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Rilascio Documento Parente (formato GG/MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_incarico',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Incarico (formato GG/MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_morte',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Morte (formato GG/MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_nascita',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Nascita (formato GG/MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_nascita_parente',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Nascita Parente (formato GG/MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='data_ora_funerale',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Ora del Funerale (formato GG/MM/YYYY hh:mm)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='ora_morte',
            field=models.TimeField(blank=True, null=True, verbose_name='Orario di Morte (formato hh:mm)'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='stato_civile',
            field=models.CharField(blank=True, choices=[('Celibe / nubile', 'Celibe / nubile'), ('Coniugato / unito civilmente', 'Coniugato / unito civilmente con'), ('Vedovo', 'Vedovo di'), ('Già coniugato / unito civolmente', 'Già coniugato / unito civolmente con')], max_length=63, null=True, verbose_name='Stato Civile'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='ubicazione_feretro',
            field=models.CharField(blank=True, choices=[('Cappella', 'Cappella'), ('Inumazione', 'Inumazione'), ('Tumulazione', 'Tumulazione')], max_length=11, null=True, verbose_name='Ubicazione Feretro'),
        ),
    ]
