# Generated by Django 5.2.5 on 2025-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0010_anagraficadefunto_sesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='data_incarico',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Incarico'),
        ),
    ]
