# Generated by Django 5.2.5 on 2025-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0011_anagraficadefunto_data_incarico'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='comune_salma',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Comune dell'osservazione salma"),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='tipo_luogo_salma',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Abitazione privata'), (2, 'Istituto / Casa di riposo')], null=True),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='via_salma',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Via dell'osservazione salma"),
        ),
    ]
