# Generated by Django 5.2.5 on 2025-08-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0012_anagraficadefunto_comune_salma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='cittadinanza',
            field=models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Cittadinanza'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='codice_fiscale',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='sesso',
            field=models.CharField(blank=True, choices=[('F', 'Femmina'), ('M', 'Maschio')], max_length=1, null=True, verbose_name='Sesso'),
        ),
    ]
