# Generated by Django 5.2.5 on 2025-08-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0013_anagraficadefunto_cittadinanza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='comune_chiesa',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune Chiesa'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='data_inumazione',
            field=models.DateField(blank=True, null=True, verbose_name='Data di inumazione'),
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='targa_autofunebre',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Targa autofunebre'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='cimitero',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune di sepoltura'),
        ),
        migrations.AlterField(
            model_name='anagraficadefunto',
            name='tipo_luogo_salma',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Abitazione privata'), (2, 'Istituto / Casa di riposo'), (3, 'struttura obitoriale')], null=True),
        ),
    ]
