# Generated by Django 5.2.5 on 2025-08-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0014_anagraficadefunto_comune_chiesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficadefunto',
            name='cimitero',
        ),
        migrations.AddField(
            model_name='anagraficadefunto',
            name='comune_inumazione',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comune di sepoltura (e provincia)'),
        ),
    ]
