# Generated by Django 5.2.5 on 2025-08-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdefunto', '0015_remove_anagraficadefunto_cimitero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficadefunto',
            name='ora_inumazione',
            field=models.TimeField(blank=True, null=True, verbose_name='Orario di inumazione'),
        ),
    ]
