# Generated by Django 5.2.5 on 2025-10-08 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='json_message',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='request_date',
        ),
        migrations.AddField(
            model_name='mail',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data di creazione'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail',
            name='template_context',
            field=models.TextField(blank=True, null=True, verbose_name='Template Context (JSON)'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di invio'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='html_text',
            field=models.TextField(blank=True, null=True, verbose_name='Rendered Html Text'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='retry',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Numero di tentativi'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Inviata'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='txt_text',
            field=models.TextField(blank=True, null=True, verbose_name='Rendered Txt Text'),
        ),
    ]
