# Generated by Django 5.2.5 on 2025-10-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_remove_mail_json_message_remove_mail_request_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='bcc_who',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='cc_who',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='from_who',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='to_who',
        ),
        migrations.AddField(
            model_name='mail',
            name='bcc',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='BCCs (as a Python list)'),
        ),
        migrations.AddField(
            model_name='mail',
            name='cc',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='CCs (as a Python list)'),
        ),
        migrations.AddField(
            model_name='mail',
            name='from_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='From email'),
        ),
        migrations.AddField(
            model_name='mail',
            name='render',
            field=models.BooleanField(default=True, verbose_name='Renderizza'),
        ),
        migrations.AddField(
            model_name='mail',
            name='to',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='TOs (as a Python list)'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Attachments (as a Python list)'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='template_context',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Template Context (JSON)'),
        ),
    ]
