# Generated by Django 5.2.5 on 2025-10-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_remove_mail_bcc_who_remove_mail_cc_who_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='template_context',
            new_name='context',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='render',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='template_name',
        ),
        migrations.AddField(
            model_name='mail',
            name='rendered',
            field=models.BooleanField(default=False, verbose_name='Renderizzata'),
        ),
        migrations.AddField(
            model_name='mail',
            name='template_html',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Template html name'),
        ),
        migrations.AddField(
            model_name='mail',
            name='template_subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Template subject name'),
        ),
        migrations.AddField(
            model_name='mail',
            name='template_txt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Template txt name'),
        ),
    ]
