# Generated by Django 5.2.5 on 2025-10-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webrequest',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
